version: '3.8'

services:

### Postgres Database###
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=userDb

  ### Postgres Database###
  app:
    container_name: user-microservice
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:5432/userDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SHOW_SQL=true


##Postgres Admin UI ###
  postgres_admin:
    image: dpage/pgadmin4:6.4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"